# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('period', models.IntegerField()),
                ('rate', models.FloatField()),
                ('calc_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'interest_rate',
            },
        ),
        migrations.CreateModel(
            name='IVIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=4)),
                ('trade_date', models.DateField()),
                ('price', models.FloatField()),
                ('ivCall30', models.FloatField()),
                ('ivPut30', models.FloatField()),
                ('ivMean30', models.FloatField()),
                ('ivCall60', models.FloatField()),
                ('ivPut60', models.FloatField()),
                ('ivMean60', models.FloatField()),
                ('ivCall90', models.FloatField()),
                ('ivPut90', models.FloatField()),
                ('ivMean90', models.FloatField()),
                ('ivCall120', models.FloatField()),
                ('ivPut120', models.FloatField()),
                ('ivMean120', models.FloatField()),
                ('ivCall150', models.FloatField()),
                ('ivPut150', models.FloatField()),
                ('ivMean150', models.FloatField()),
                ('ivCall180', models.FloatField()),
                ('ivPut180', models.FloatField()),
                ('ivMean180', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'iv_index',
            },
        ),
        migrations.CreateModel(
            name='RawIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=4)),
                ('trade_date', models.DateField()),
                ('stock_close_price', models.FloatField()),
                ('option_symbol', models.CharField(max_length=5)),
                ('expiration', models.DateField()),
                ('strike', models.FloatField()),
                ('call_or_put', models.CharField(max_length=1)),
                ('ask', models.FloatField()),
                ('bid', models.FloatField()),
                ('mean_price', models.FloatField()),
                ('iv', models.FloatField()),
                ('volume', models.IntegerField()),
                ('stock_price_for_iv', models.FloatField()),
                ('isinterpolated', models.CharField(max_length=1)),
                ('delta', models.FloatField()),
                ('vega', models.FloatField()),
                ('gamma', models.FloatField()),
                ('theta', models.FloatField()),
                ('rho', models.FloatField()),
            ],
            options={
                'managed': False,
                'db_table': 'raw_iv',
            },
        ),
        migrations.CreateModel(
            name='YieldRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('symbol', models.CharField(max_length=3)),
                ('yield_rate', models.FloatField()),
                ('calc_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'yield_rate',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, max_length=200)),
                ('path', models.FilePathField(recursive=True, verbose_name='/')),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('path', models.FilePathField(recursive=True, verbose_name='/home/zh/Finance/upload')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveSmallIntegerField(default=2333)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.SmallIntegerField(choices=[(-2, 'Wrong'), (-1, 'Stopped'), (0, 'Finished'), (1, 'Waiting'), (2, 'Starting'), (3, 'Running'), (4, 'Stopping')], default=1)),
                ('ret', models.IntegerField(null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.App')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('blank', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.App')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='app',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Host'),
        ),
        migrations.AddField(
            model_name='app',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
